version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: bookstore-db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_pass
    command: postgres -c timezone=Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    container_name: bookstore
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookstore
      SPRING_DATASOURCE_USERNAME: bookstore_user
      SPRING_DATASOURCE_PASSWORD: bookstore_pass
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: