spring:
  application:
    name: bookstore

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: ERROR
